{
 "title": "SonarQube",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "projectName",
    "label": "项目",
    "query": "label_values(sonarqube_bugs, name)"
   },
   {
    "name": "id",
    "label": "ID",
    "query": "label_values(sonarqube_bugs{name=\"$projectName\"},key)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bug数",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_bugs{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "漏洞数",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "单元测试覆盖率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "技术债务（天）",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_sqale_index{name=\"$projectName\"}/60/8"
    }
   ]
  },
  {
   "title": "阻断等级问题数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_blocker_violations{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "严重等级问题数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_critical_violations{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "重要等级问题数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_major_violations{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "次要等级问题数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_minor_violations{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "提示等级问题数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_info_violations{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "代码行数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_ncloc{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "代码异味数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "重复文件数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_duplicated_files{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "重复块数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_duplicated_blocks{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "重复代码行数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_duplicated_lines{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "重复文件数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_duplicated_files{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "认知复杂度",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarqube_cognitive_complexity{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "单元测试覆盖率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonarqube_coverage{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "代码异味数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonarqube_code_smells{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "重复代码行数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonarqube_duplicated_lines{name=\"$projectName\"}"
    }
   ]
  },
  {
   "title": "代码行数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonarqube_ncloc{name=\"$projectName\"}"
    }
   ]
  }
 ]
}